name: Bug report
description: If you've found a problem with the template, let us know so that we can update it for everyone.
labels:
  - 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in helping improve the Platform.sh templates!
        Please fill in the fields below so we can understand what's going wrong.

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend diam non condimentum tincidunt. Vestibulum convallis eget ante dapibus eleifend.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Include some logs
      description: Any logs you can include will help us investigate the issue.
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend diam non condimentum tincidunt. Vestibulum convallis eget ante dapibus eleifend.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproducing
      description: Help us reproduce what you're seeing.
      placeholder: | 
          Steps to reproduce the behavior:
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend diam non condimentum tincidunt. Vestibulum convallis eget ante dapibus eleifend.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your environment
      description: Give us as many details as you can about your environment, whether that's on Platform.sh (your configuration YAMLs), or locally (your OS, services, and local development tool).
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend diam non condimentum tincidunt. Vestibulum convallis eget ante dapibus eleifend.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: A picture's worth a thousand words...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Optionally add any other information or screenshots that could help us understand and implement the change.
      placeholder: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eleifend diam non condimentum tincidunt. Vestibulum convallis eget ante dapibus eleifend.
    validations:
      required: false
  