blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://community.platform.sh/
    about: Please ask and answer questions here.
  - name: Join us on Slack
    url: https://chat.platform.sh/
    about: Ping the `@devrel_team`!
