name: Feature request
description: For changes to improve this template.
labels:
  - 'feature request'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in helping improve the Platform.sh templates!
        Please fill in the fields below so we can understand what changes you'd like to see.

  - type: textarea
    attributes:
      label: What in this template can be improved or added as a feature?
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: What exactly should be updated?
      description: |
        - Share as much detail as you can to help us understand the suggestion. 
        - What do you expect as an outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: How important is this feature to you?
      description: Does this template lacking this feature block your work?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Optionally add any other information or screenshots that could help us understand and implement the change.
    validations:
      required: false
